name: algo_pass
description: Eat me

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+3
  flutter_secure_storage: ^3.3.3
  url_launcher: ^5.4.5
  clipboard_manager: ^0.0.4
  flutter_plugin_android_lifecycle: ^1.0.7
  intro_slider: ^2.2.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  local_auth: ^0.6.1+3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/config_algo.png
    - assets/remeber_algo.png
    - assets/further_config_algo.png
    - assets/name_algo.png
    - assets/security.png


  fonts:
    - family:  Custom
      fonts:
        - asset: fonts/Custom.ttf

    - family: Mono
      fonts:
        - asset: fonts/mono.ttf

    - family: Courier
      fonts:
        - asset: fonts/courier.ttf
